### ISSUE TITLE
Plugin breaks left menu on strapi 3.6.0

### ISSUE THREAD

**Issue by cruonline** [nicolashmln/strapi-plugin-responsive-image#10]
After updating to Strapi 3.6.0.  last section of menu (general) with store and settings is missing.
Uninstalling this plugin, resolves issue.

**Comment by nicolashmln** [comment]
Okay thanks for letting me know. I cannot test a the moment because of this issue #9

**Comment by nicolashmln** [comment]
Fixed in 0.4
Looks like adding the permissions for the settings page fixed the problem
