### ISSUE TITLE
sharp issue on strapi 3.6.8

### ISSUE THREAD

**Issue by cruonline** [nicolashmln/strapi-plugin-responsive-image#13]
Hi,

I have just run into some issues with sharp after updating to the latest strapi (3.6.8) and responsive-image 0.5.0

`Something went wrong installing the "sharp" module`

Rolling pack responsive-image to 0.4.0 solves the problem.
I have noticed, you have bumped sharp dep, to 0.29.0 however, strapi is still on 0.28.1

So, question is, why not move sharp dependency, to peer dependencies, so we rely on packages already in place from strapi?

**Comment by nicolashmln** [comment]
To have the lastest updates for the avif format.

Did you try to remove the `package-lock.json` file and the `node_modules` folder and run the `npm install`? I have tested with the 3.6.8 version of strapi and I have no problem.

**Comment by cruonline** [comment]
I have tried clean install, with both node_modules and yarn-lock deleted.
(Also, using yarn, not npm, and windows 10 for good measure :) )
I guess I will stick to 0.4.0 until strapi updates sharp to the latest
version.


śr., 22 wrz 2021 o 13:14 nicolashmln ***@***.***> napisał(a):

**Comment by dirq** [comment]
I get the same problem with Sharp.  Windows 10.  Moved back to 0.4.0 and it runs BUT I wanted this for the webp support.

**Comment by cruonline** [comment]
I guess no love for devs on windows machines ;-)
