### ISSUE TITLE
Compatibility with Strapi v4

### ISSUE THREAD

**Issue by nicolashmln** [nicolashmln/strapi-plugin-responsive-image#17]
Work in progress

**Comment by cortopy** [comment]
master branch seems to already have the migrated v4 folder structure. Is there anything else that's needed for v4?

**Comment by nicolashmln** [comment]
@cortopy Strapi v4 don't detect the plugin. I didn't try again the new updates of the v4. I'll try to spend some times on it soon.

**Comment by abelcabezaroman** [comment]
Thanks @nicolashmln for your work

**Comment by anupam-codeprism** [comment]
@nicolashmln any progress on fixing it?

**Comment by nicolashmln** [comment]
@anupam-codeprism yes, the plugin is now detected, I'm plugged on the settings but I have some packages missing when I look at the settings from the admin UI. Don't know what's the problem for now.

**Comment by Krislunde** [comment]
Any updates on this? Strapi 4 has been out for a while now. Is the plugin abandoned?

**Comment by nicolashmln** [comment]
@Krislunde I have some struggles to adapt to v4 (some stuff doesn't work as expected on the strapi side) and I didn't have enough time to work on that for the moment. But it will be updated at some point

**Comment by smartfox87** [comment]
Any updates on this?

**Comment by nicolashmln** [comment]
Status update: All the settings screen is done, need to override image manipulation now

**Comment by nicolashmln** [comment]
v1.0.0 is now compatible with v4. Please have a try and open an issue if needed. Thanks
