### ISSUE TITLE
Sharp module version

### ISSUE THREAD

**Issue by DominicBisschop** [nicolashmln/strapi-plugin-responsive-image#18]
When I tried to use your npm package, I constantly got an error with module errors with sharp. So I searched the internet and tried several things. The only thing that worked for me was:
- Deleting node_module package for sharp
- Updated the sharp module to the latest version in the package.json of your plugin
- After that it worked like a charm!

Can you update your package so it always uses the latest or stable version of sharp? That would mean we don't have to run post deployment scripts to update the version everytime!

Great plugin and thanks in advance!

Greetings,
Dominic Bisschop

**Comment by abelcabezaroman** [comment]
My project is working fine installing both packages...this one and sharp with below versions:

- 0.5.0 version --> sharp version 0.28.1
- 0.4.0 version --> latest sharp version  0.30.1 for example 

I hope this help :)

**Comment by nicolashmln** [comment]
Closing this as the v3 is not maintained anymore
