### ISSUE TITLE
Wrong formats when upload webp image to Strapi

### ISSUE THREAD

**Issue by Sergei8888** [nicolashmln/strapi-plugin-responsive-image#19]
I have configured formats:
![image](https://user-images.githubusercontent.com/45688549/148596737-d1857759-9055-4544-b1fd-21d06330d233.png)
If i upload jpeg image all works fine, formats are correct:
![image](https://user-images.githubusercontent.com/45688549/148596970-46fd0b38-dffd-4c85-9d89-0059001c1a79.png)
![image](https://user-images.githubusercontent.com/45688549/148596923-1b57e9ae-396f-470a-81ed-61c682416e84.png)
But if i upload webp directly:
![image](https://user-images.githubusercontent.com/45688549/148597145-8f90bfc2-bce0-466d-9ac1-cbb4667c78a9.png)
![image](https://user-images.githubusercontent.com/45688549/148597408-a459ce15-4bc7-4101-b7f1-f4eeeddd3f75.png)
There are only basic image formats, not mine

**Comment by nicolashmln** [comment]
Thanks, I'll have a look

**Comment by nicolashmln** [comment]
Closing this as the v3 is not maintained anymore
