### ISSUE TITLE
Settings are not rendered at Strapi 3.1.3

### ISSUE THREAD

**Issue by SalahAdDin** [nicolashmln/strapi-plugin-responsive-image#2]
Thank for this good plugin, it works very well.

Today i just updated my project to **3.1.3** and i got the next book:
![Screen Capture_select-area_20200806004911](https://user-images.githubusercontent.com/5034215/89467903-1e74a200-d77f-11ea-8219-82abb77000cd.png)
I can see its panel in the settings.

But it is installed:
![Screen Capture_select-area_20200806004858](https://user-images.githubusercontent.com/5034215/89467922-27fe0a00-d77f-11ea-9e86-f2ec9fa4772b.png)

What's the problem here?

**Comment by AlexTechNoir** [comment]
Same here with 3.1.4

**Comment by nicolashmln** [comment]
Fixed in v0.2.0 (tested with strapi 3.1.5)
Thank you
