### ISSUE TITLE
Doesn't work with Latest Strapi 4.1.1

### ISSUE THREAD

**Issue by siamekanto19** [nicolashmln/strapi-plugin-responsive-image#20]
## Issue

I have installed the plugin in Strapi v4.1.1 with `npm install strapi-plugin-responsive-image` and it installed the 0.5.0 version of this plugin in the project. I have also followed the instructions as written. Created all the folders and files as instructed in Readme. 

But it didn't work. I restarted the Strapi server with `npm run develop` but in the plugins menu, Strapi does not detect the plugin and also does not show the image related options provided by the plugin in settings menu.

## Reproduction Steps

- Initialize a new Strapi Project using Strapi v4.1.1 or upgrade an existing project to 4.1.1
- Install the plugin bu running ``npm install strapi-plugin-responsive-image``
- Create the new folders and `image-manipulation.js` file as instructed by this plugin's Readme.
- Start Strapi server with `npm run develop`.

@nicolashmln

**Comment by Cawet** [comment]
Hello, exact same issue for me here!

**Comment by nicolashmln** [comment]
Yeah, it's not compatible yet, eg #17
