### ISSUE TITLE
Documentation setup error

### ISSUE THREAD

**Issue by designeng** [nicolashmln/strapi-plugin-responsive-image#23]
"So we need to add a strapi-server.js file within the src/extensions/upload/strapi-server.js folder" - you probably meant " within the src/extensions/upload folder" ?

Should be 
```
mkdir -p src/extensions/upload
touch src/extensions/upload/strapi-server.js
```

**Comment by cwerner1** [comment]
I created a pull Request for the Issue 
https://github.com/nicolashmln/strapi-plugin-responsive-image/pull/24

**Comment by nicolashmln** [comment]
thanks
