### ISSUE TITLE
Doesn't work in a Typescript project

### ISSUE THREAD

**Issue by ciriousjoker** [nicolashmln/strapi-plugin-responsive-image#29]
The installation instructions don't work because the .js file isn't detected, even though modifying it forces a recompilation.

**Comment by ciriousjoker** [comment]
Fixed it:

```ts
const imageManipulation = require("strapi-plugin-responsive-image/server/services/image-manipulation");

// console.log("FOUND");
export default (plugin) => {
  plugin.services["image-manipulation"] = imageManipulation();

  // console.log("LOADED");
  return plugin;
};
```

Also, the brackets are necessary, otherwise you get an error message like "isImage is not a function".

---

I would have closed this, but changing the installation instructions with a bit more information might be helpful.

**Comment by nicolashmln** [comment]
Installation instruction updated, thanks
