### ISSUE TITLE
Plugin not replacing the upload plugin

### ISSUE THREAD

**Issue by Dirvann** [nicolashmln/strapi-plugin-responsive-image#33]
strapi-version: 4.10.7, but also tested with 4.10.5
lang: typescript

- I added the strapi-server.js file in src/extensions/upload/strapi-server.js

- I copied the typescript code that had to be put in there :
```javascript
const imageManipulation = require("strapi-plugin-responsive-image/server/services/image-manipulation");

export default (plugin) => {
  plugin.services["image-manipulation"] = imageManipulation();

  return plugin;
};
```

- I ran `npm run build` and started the server
- I changed a few options like the name of the formats and output format in the settings of the plugin
- When uploading a new file only the standard (small, medium, large, thumbnail) sizes from the upload plugin are present. 

I also tried with the js version in strapi-server.js but also not having an effect

## Expected behavior
- the files are in the format set in responsive image plugin

**Comment by svenruegg** [comment]
should be a .ts file when using typescript, no?

**Comment by Dirvann** [comment]
@svenruegg  Thanks for the reply. 

The upload plugin actually has a js file, in the readme it also sais to just use a js file for typescript.
But I also tried with .ts but that also did not have any effect.

**Comment by svenruegg** [comment]
Hi @Dirvann

Ok, that's a pity.
I am using the ts version as well and your script looks like mine. 
I am using Strapi 4.11.0 though where it works but don't think that thats the problem.

Have you tried to delete the node modules folder and the package.lock.json and run npm i again?

**Comment by Dirvann** [comment]
Oh good to hear that it works, i will try again with version 4.10.8 ( because for some reason there is an issue when I upgrade to 4.11).

**Comment by Dirvann** [comment]
@svenruegg  Thanks! It worked

I upgraded to 4.11.0.
- removed node_modules
- removed package-lock
- installed packages
- ran the build
- changed the file type to .ts
Then it worked!

So a good refresh was needed

Thanks for the help!

**Comment by Dirvann** [comment]
Created PR with the clarification in the documentation #36
