### ISSUE TITLE
WebP as image format

### ISSUE THREAD

**Issue by valoricDe** [nicolashmln/strapi-plugin-responsive-image#5]
Hi. Currently I use strapi in combination with gatsby. And gatsby is everytime downloading and converting the images to webp. I think it would be awesome if this step could be migrated to strapi as it would be a one-of job.
What do you think about it?

**Comment by nicolashmln** [comment]
Hi, I'm not sure what you mean. You ask for an option to convert an image to webp when you upload it?
Like you upload a .jpg and the plugin convert it to a .webp (with the responsive images associated)?

**Comment by valoricDe** [comment]
Yes, that is exactly what I thought of

**Comment by nicolashmln** [comment]
Okay, could be a good idea yeah. I'm not sure if I can do that quickly but that's definitely in the todo list

**Comment by webzlodimir** [comment]
We are really looking forward to converting to webp, thanks!

**Comment by stuible** [comment]
Would also love this. Thanks for filling an important gap in Strapi functionality!

**Comment by nicolashmln** [comment]
Done in v0.5
