### ISSUE TITLE
Multiple responsive image types

### ISSUE THREAD

**Issue by yusufisl** [nicolashmln/strapi-plugin-responsive-image#6]
Hello, thank you for your great plugin, love it.

I have a question, sometimes we have different image breakpoints in some use cases. (ex: user avatar and product thumbnail).

Do you have plan to make it happen ?

**Comment by nicolashmln** [comment]
Thank you.

At the moment the strapi media library plugin doesn't give the ability to have different breakpoints for different use cases (eg. having the breakpoint `avatar` for the field `photo` in the content type `user`). I think you can ask this feature directly to the strapi team.
What you can do with this plugin is define all your breakpoint's use cases and when you upload an image you'll have all the formats. I understand for some images some breakpoints won't be used, but that's the best we can do at the moment.
